### ISSUE TITLE
error on export for Ad Hoc

### ISSUE THREAD

**Issue by mvayngrib** [iProov/ios#3]
i'm not an xcode expert. Does this look familiar? :)

```sh
2017-06-09 03:43:34 +0000 [MT] Presenting: Error Domain=IDEFoundationErrorDomain Code=1 "Failed to verify bitcode in iProov.framework/iProov:
error: Bundle only contains bitcode-marker /var/folders/ty/79wqqmzs5jz0kxs0fdtrg_zm0000gn/T/IDEDistributionThinningStep.iGd/Payload/Tradle.app/Fram…" UserInfo={NSLocalizedDescription=Failed to verify bitcode in iProov.framework/iProov:
error: Bundle only contains bitcode-marker /var/folders/ty/79wqqmzs5jz0kxs0fdtrg_zm0000gn/T/IDEDistributionThinningStep.iGd/Payload/Tradle.app/Fram…}
```

**Comment by soupangel** [comment]
@mvayngrib this issue should be resolved with SDK 5.1.2. Please re-open if build errors persist.

**Comment by mvayngrib** [comment]
@soupangel cool, thanks! I'm having trouble installing sdk 5.1.2. In my Podfile I have:

```
  pod 'iProov', :git => 'https://github.com/iProov/iproov-ios-pod.git'
```

when I run `pod install --repo-update`, it installs 5.1.0

**Comment by soupangel** [comment]
Hi Mark, could you try `pod update` and see if that pulls the right
version? (FYI as of today we are on 5.2.1).

If not, what happens if you try manually specifying the version number in
your podfile?

**Comment by mvayngrib** [comment]
@soupangel that worked, thanks! Funny, I thought `pod install --repo-update` was supposed to take care of that...

**Comment by soupangel** [comment]
I believe --repo-update downloads the latest repo spec yes, but doesn't
necessarily apply new versions it finds there; so your podfile.lock
probably still referenced the old version. In contrast, pod update actually
ignores your podfile.lock so it will hunt for the latest version of every
pod which doesn't have an exact version specified.

Glad it's all working and enjoy your weekend!



On 14 Jul 2017 19:25, "Mark Vayngrib" <notifications@github.com> wrote:

@soupangel <https://github.com/soupangel> that worked, thanks! Funny, I
thought pod install --repo-update was supposed to take care of that...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/iProov/ios/issues/3#issuecomment-315432126>, or mute
the thread

**Comment by mvayngrib** [comment]
@soupangel ah, ic, thanks for clearing that up :)
